plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    // Jared's Maven for JEI
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    // ModMaven fallback for JEI
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

dependencies {
    // Minecraft and Loader
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // JEI Integration (Optional)
    // Compiles against the API so your mod builds cleanly
    compileOnly "mezz.jei:jei-${project.minecraft_version}-fabric-api:30.15.0.121"
    // Loads full JEI in your dev environment (runClient) for testing, but won't nest it in your released JAR
    runtimeOnly "mezz.jei:jei-${project.minecraft_version}-fabric:30.15.0.121"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}"}
    }
}

// Configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {
        // Add repositories to publish to here.
    }
}